# version format
version: "0.6.4"

init:
  - set MAYBE_PRERELEASE_SUFFIX=

build_script:
  - build.cmd

test_script:
 - dotnet test CallMeMaybe.UnitTests\CallMeMaybe.UnitTests.csproj

artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'

deploy:
  # NuGet Deployment for builds & releases
  - provider: NuGet
    api_key:
      secure: IY6agMq2688v7szuA4Gdz433XY3olqrT5SMv3iVker6rKzcWXUz8wrRb15sSPFA3
    artifact: /.*\.nupkg/
    on:
      branch: master